### PR TITLE
change link hover over color

### PR DESCRIPTION
**Pull request by KellyAH**
- for https://github.com/zinc-collective/www.zinc.coop/issues/103
requested in https://github.com/zinc-collective/www.zinc.coop/issues/103#issuecomment-1593369657

Link color:
FE9BFF zinc-pastel-pink

Hover over lnk color:
C966CA zinc-darker-pastel-pink

change link hover color

### CODE REVIEW

**Review by zspencer — APPROVED** [review]
Thanks! This is a substantative improvement; I could imagine taking some time to ensure that the contrast between text and background on hover is WCAG compliant (https://whocanuse.com) ; since darkening into a dark background can be a bit of a challenge.

**Comment by KellyAH** [comment]
🚀 deployed and ✅ verified on prod 💃

**Comment by KellyAH** [comment]
@zspencer 
Darn the color I changed the hover link color to, `'zinc-darker-pastel-pink': '#C966CA'` , **fails** 🔴  WCAG compliance.
zinc-darker-pastel-pink fails

`'zinc-hot-pink': '#F43EF3'` fails WCAG compliance too.
zinc-hot-pink fails

Changing the :hover link color to a lighter pastel pink doesn't work even if it's WCAG compliance. It's too close to the current link color of `'zinc-pastel-pink': '#FE9BFF'` thus it's tough to tell when a link is hovered over.

You didn't like the teal but about a different color?

Which of these WCAG compliant hover link colors do you prefer and are easy to see? Pick one and I'll change the :hover link color to it.
h-blue 9BE4FF
h-green 9BFFA3
h-purple A79BFF
h-red FF9B9B
h-yellow FFE99B

**Comment by zspencer** [comment]
Seeing as we're struggling to pass WCAG sniff tests with our current color pallet,  I wonder if we would be better suited by using https://tailwindcss.com/docs/customizing-colors directly.

Then we could just lighten the color by doing something like `text-purple-500 hover:textpurple-400` (or 350 or whatever) until we find the step that is WCAG compliant.

**Comment by KellyAH** [comment]
The current background colors (`'zinc-purple': '#332658', 'zinc-dark-purple': '#1F1735',`) and text color (`'zinc-pastel-pink': '#FE9BFF',`) are fine and pass WCAG compliance. 

Just the :hover text color `'zinc-darker-pastel-pink': '#C966CA'` I chose for this PR, is failing WCAG compliance. 

Just pick one of the WCAG compliant hover link colors I pasted above for the :hover link color. Or choose white, that passes WCAG compliance too. 

Screenshot 2023-06-16 at 9 56 31 PM

I need to wrap up work on https://github.com/zinc-collective/www.zinc.coop/issues/103 ASAP soon so I can dive back into the more difficult Rails work for my convene assigned issues.

**Comment by anaulin** [comment]
Let's go with either white or with this one:
image

**Comment by anaulin** [comment]
(I don't think the Tailwind standard colors help in this case, because they don't have any actual palettes or sets of colors that would be WCAG compliant, as far as I can see. We still have to choose our own colors.)

**Comment by zspencer** [comment]
I agree with @anaulin; white or the purple is great!

**Pull request merged**
