### PR TITLE
remove Project Guidelines and Become a Maintainer pages

### PR DESCRIPTION
**Pull request by KellyAH**
- For https://github.com/zinc-collective/www.zinc.coop/issues/103

remove Project Guidelines and Become a Maintainer pages as Zee requested in https://github.com/zinc-collective/www.zinc.coop/issues/103#issuecomment-1586255254

more changes

### CODE REVIEW

**Comment by KellyAH** [comment]
@zspencer `project maintainer` is mentioned all over the [code-of-conduct page](https://github.com/zinc-collective/www.zinc.coop/blob/development/src/code-of-conduct.md). Should `project maintainer` be replaced with something else? 

Screenshot 2023-06-12 at 6 13 22 PM

**Review by zspencer — APPROVED** [review]
Thank you!

**Comment by KellyAH** [comment]
🚀 deployed and ✅ verified on prod 💃

**Comment by KellyAH** [comment]
> `project maintainer` is mentioned all over the [code-of-conduct page](https://github.com/zinc-collective/www.zinc.coop/blob/development/src/code-of-conduct.md). Should `project maintainer` be replaced with something else?

I discussed this with @zspencer and we agreed that "project maintainer" can stay on the code-of-conduct page. It is a generic understood term in the coding community. The removal of the "Become a Maintainer pages" will not confuse visitors of the website.

**Pull request merged**
